version: "3.9"
services:
  goodoorAPI:
    container_name: goodoor-api
    build: .
    environment:
      DATABASE_URL: "host=goodoor_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - goodoor_db
  goodoor_db:
    container_name: goodoor_db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5300:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
